# Generated by Django 4.0.1 on 2023-03-30 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('play_cricket_ID', models.IntegerField()),
                ('team_badge', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='FixtureUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_cricket_fixture_ID', models.IntegerField()),
                ('last_updated', models.DateField()),
                ('status', models.CharField(max_length=50)),
                ('match_date', models.DateField()),
                ('match_time', models.CharField(max_length=50)),
                ('ground_name', models.CharField(max_length=150)),
                ('ground_ID', models.CharField(max_length=50)),
                ('home_team_name', models.CharField(max_length=150)),
                ('competition_type', models.CharField(max_length=150)),
                ('away_club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_club', to='home.clubs')),
                ('home_club_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_club', to='home.clubs')),
            ],
        ),
    ]
