# Generated by Django 4.0.1 on 2023-03-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_clubs_team_badge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixtures',
            name='home_team_name',
        ),
    ]
