# Generated by Django 4.0.1 on 2023-03-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_fixtures_home_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='luddes_team',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
